### ISSUE TITLE
Can you open DPG programme in mujoco environment? 

### ISSUE THREAD

**Issue by www2171668** [aditimavalankar/option-keyboard#1]
Hi, Can you open DPG programme in mujoco environment about chapter 5.2？Thank you

**Comment by www2171668** [comment]
> Hi, Can you open DPG programme in mujoco environment about chapter 5.2？Thank you

**Comment by aditimavalankar** [comment]
Sorry for the late response; since I did not have a Mujoco license, I only reproduced results on the Foraging World environment.
